FROM golang:1.22.4-alpine3.19 AS builder

WORKDIR /app

COPY . .

RUN go build -o publisher ./publisher/publisher.go

FROM alpine:latest

WORKDIR /app/
COPY --from=builder /app/publisher .

ENTRYPOINT [ "./publisher" ]